name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: great
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-great: Will
      - name: Log Greeting Time
        run: echo "${{ steps.great.outputs.time }}"