name: Actions Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: great
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Will
      - name: Log Greeting Time
        run: echo "${{ steps.great.outputs.time }}"